apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"      # 200 milliCPU (0.2 CPU)
            memory: "256Mi"  # 256 Mebibytes
          requests:
            cpu: "100m"      # 100 milliCPU (0.1 CPU)
            memory: "128Mi"  # 128 Mebibytes